name = "joptan"
uuid = "9b31a882-e68d-43d9-8f5a-83b5e2d33d80"
authors = ["Le Nhut Nam"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
